
name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./data-structures/LinkedList.sln
    - name: Build
      run: dotnet build ./data-structures/LinkedList.sln --configuration Release
    - name: Test
      run: dotnet test ./data-structures/LinkedList.sln --configuration Release